name: Sync to Azure 'feature' Branch

on:
  push:
    branches:
      - feature-*

jobs:
  sync:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITPAT }}

    - name: Add Azure remote
      run: git remote add azure ${{ secrets.AZURE_REPO_URL }}
    
    - name: Configure Git
      run: |
        git config user.email "alex.nava.developer@outlook.com"
        git config user.name "Alex Nava"
  
    - name: Fetch latest changes from Azure
      run: git fetch azure feature

    - name: Merge feature branch into GitHub 'feature' branch
      run: |
        git checkout --track origin/feature
        git merge --no-ff ${{ github.ref }}
        git push origin feature

    - name: Merge feature branch into Azure 'feature' branch
      run: |
        git checkout azure/feature
        git merge --no-ff ${{ github.ref }}
        git push azure feature